genome: hg38
ensembl_genome_build: 110
viral_genome: #https://www.ncbi.nlm.nih.gov/datasets/genome/
  apply: False # whether to include viral genome in analysis
  name: Human betaherpesvirus 5
  genome_assembly: ViralProj14559
  NCBI_RefSeq_assembly: GCF_000845245.1
star:
  index:
    extra: ""
  align:
    extra: ""
stranded: yes # unstranded, yes, reverse (as htseq-count -s values)
fdr_cutoff: 0.05 # cut off for volcano plots
fc_cutoff: 0.5 # log2 fold change cut off for volcano plots
deeptools:
  normalisation: RPKM # RPKM, CPM, BPM, RPGC, None
  binsize: 10
resources: # computing resources
  trim:
    cpu: 8
    time: 60
  fastqc:
    cpu: 4
    time: 20
  star_index:
    cpu: 32
    time: 60
  mapping:
    cpu: 12
    time: 60
  samtools:
    cpu: 4
    time: 30
  deeptools:
    cpu: 6
    time: 60
  deseq2:
    cpu: 6
    time: 60 
  plotting:
    cpu: 2
    time: 10
