# Reference genome parameters
# --------------------------------------
genome: test
ensembl_genome_build: 110

# Optional viral genome parameters
# --------------------------------------
# Viral genomes have to be from NCBI Datasets
#https://www.ncbi.nlm.nih.gov/datasets/genome/
viral_genome:
  apply: False # whether to include viral genome in analysis
  name: Human betaherpesvirus 5
  genome_assembly: ViralProj14559
  NCBI_RefSeq_assembly: GCF_000845245.1

# STAR (alignment) parameters
# --------------------------------------
star:
  index:
    extra: ""
  align:
    extra: ""

# DESeq2 parameters
# --------------------------------------
# Check https://htseq.readthedocs.io/en/latest/htseqcount.html for more info on stranded option
stranded: unstranded # QUOTE if yes! unstranded, yes, reverse (as htseq-count -s values)
lfc_shrinkage: FALSE # whether to apply log fold change shrinkage in DESeq2 analysis
fdr_cutoff: 0.05 # cut off for volcano plots
fc_cutoff: 0.5 # log2 fold change cut off for volcano plots

# BigWig parameters for deepTools
# --------------------------------------
deeptools:
  normalisation: RPKM # RPKM, CPM, BPM, RPGC, None
  binsize: 1000

# Computing resources
# --------------------------------------
resources:
  trim:
    cpu: 8
    time: 60
  fastqc:
    cpu: 4
    time: 20
  star_index:
    cpu: 32
    time: 60
  mapping:
    cpu: 12
    time: 60
  samtools:
    cpu: 4
    time: 30
  deeptools:
    cpu: 6
    time: 60
  deseq2:
    cpu: 6
    time: 60
  plotting:
    cpu: 2
    time: 10
