$schema: "http://json-schema.org/draft-07/schema#"
description: Schema to validate Snakemake configuration file

type: object

properties:
  genome:
    type: string
    enum: ["hg19", "hg38", "mm38", "mm39", "test"]
    description: Genome build to use for alignment

  ensembl_genome_build:
    type: integer
    description: Ensembl genome build version
  
  viral_genome:
    type: object
    properties:
      apply:
        type: boolean
        description: Whether to include viral genome in analysis
      name:
        type: string
        description: Name of the viral genome
      genome_assembly:
        type: string
        pattern: "^ViralProj[\\d]{5}$"
        description: Genome assembly name
      NCBI_RefSeq_assembly:
        type: string
        pattern: "^GCF_[\\d]{9}\\.[\\d]+$"
        description: NCBI RefSeq assembly name

    required:
      - apply
      - name
      - genome_assembly
      - NCBI_RefSeq_assembly

  star:
    type: object
    properties:
      index:
        type: object
        properties:
          extra:
            type: string
            description: Additional arguments to pass to STAR index
      align:
        type: object
        properties:
          extra:
            type: string
            description: Additional arguments to pass to STAR align

    required:
      - index
      - align

  #stranded:
  #  type: string
    #enum: ["unstranded", "yes", "reverse"]
    description: Strandedness of the RNA-seq library

  fdr_cutoff:
    type: number
    minimum: 0
    maximum: 1
    description: Cut off for volcano plots

  fc_cutoff:
    type: number
    minimum: 0
    description: Log2 fold change cut off for volcano plots

  deeptools:
    type: object
    properties:
      normalisation:
        type: string
        enum: ["RPKM", "CPM", "BPM", "RPGC", "None"]
        description: Normalisation method
      binsize:
        type: integer
        minimum: 1
        description: Bin size for deeptools
  
    required:
      - normalisation
      - binsize
  
  resources:
    type: object
    properties:
      trim:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
            minimum: 1
      fastqc:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
            minimum: 1
      star_index:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
            minimum: 1
      mapping:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
            minimum: 1
      samtools:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
            minimum: 1
      deeptools:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
            minimum: 1
      deseq2:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
            minimum: 1
      plotting:
        type: object
        properties:
          cpu:
            type: integer
            minimum: 1
          time:
            type: integer
            minimum: 1